#!/bin/bash

if [ "$#" != 2 ]
then
	echo 'musia byt dva argumenty'
	exit 1
fi

DAY=$(echo $1 | cut -c1-2)
MONTH=$(echo $1 | cut -c4-5)
YEAR=$(echo $1 | cut -c7-11)

SEARCH_ARG=$(echo "$MONTH/$DAY/$YEAR")
START_TIME=$(date -d "$SEARCH_ARG" +'%s')
END_TIME=$(echo "$START_TIME + 24*60*60" | bc)
echo "$END_TIME"

URL='https://aviationweather.gov/adds/dataserver_current/httpparam?dataSource=metars&requestType=retrieve&format=csv&stationString='"$2"'&startTime='"$START_TIME"'&endTime='"$END_TIME"''
curl -s "$URL" |
	grep  "$2"
